- .dockerignore
- .github/pull_request_template.md
- .github/workflows/analyzer.yml
- .github/workflows/builder.yml
- .github/workflows/deployer.yml
- .github/workflows/mlc_config.json
- .github/workflows/rcb_config.json
- .github/workflows/tester.yml
- .maintain/docker/Dockerfile
- .maintain/docker/build-image.sh
- .maintain/docker/create-network.sh
- .maintain/docker/docker-compose.yml
- .maintain/docker/start-docker-compose.sh
- .maintain/docker/stop-docker-compose.sh
add GitHub workflows & docker scripts
> Add GitHub Workflows & Docker Scripts

- gatsby-node.js
- added gatsby-node for build
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
- Feature
- Bug
- Refactor
- Test
- Documentation
> fix: added gatsby-node for build

- src/components/Empty/Empty.js
- src/components/Empty/Empty.styles.js
- src/components/Empty/index.js
- src/components/ServerList/ServerList.container.js
- feat: wired search component, tag
- open instance in new tab
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
- Feature
- Bug
- Refactor
- Test
- Documentation
> feat: wired search component, tag

- src/components/ServerList/ServerList.container.js
- src/components/ServerList/serverlist.styles.js
- fix: show list uncomplele data instance
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
- Feature
- Bug
- Refactor
- Test
- Documentation
> fix: show list uncomplele data instance

- .github/workflows/builder.yml
- N/A
ci: update create draft release
> ci: update create draft release

- .github/workflows/builder.yml
> ci: fixed draft release

- .github/pull_request_template.md
- .github/workflows/builder.yml
- .github/workflows/create-tags.yml
- .github/workflows/deployer.yml
- .github/workflows/release.yml
- .github/workflows/update-version.yml
- [MYR-2248]
create tag, remove development environment, change pull request template
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
- Feature
- Bug
- Refactor
- Test
- Documentation
- CI
[MYR-2248]: https://blocksphere2020.atlassian.net/browse/MYR-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: improve ci-cd

- .github/workflows/create-tags.yml
- .github/workflows/deployer.yml
- .github/workflows/release.yml
ci: fix create tags & release
N/A
> ci: fix create tags & release

- .github/workflows/deployer.yml
ci: added new env
https://blocksphere2020.atlassian.net/browse/MYR-2486
> ci: added new env

- .github/workflows/deployer.yml
> ci: fixed permission

- .github/workflows/deployer.yml
> ci: fix deployment

- next.config.js
- package.json
- src/components/ServerList/ServerList.tsx
- src/layout/ContentLayout.tsx
- src/pages/index.tsx
- src/pages/instance/index.tsx
- yarn.lock
> update env & fix bug

- next.config.js
- src/components/ServerList/ServerList.tsx
- src/components/atoms/CardInstance/index.tsx
- src/lib/services/polkadot-js.ts
- src/pages/dashboard/user/index.tsx
- src/pages/dashboard/user/responded.tsx
- src/utils/numberFormatter/index.ts
https://blocksphere2020.atlassian.net/browse/MYR-2475
> fix: url report user

- src/components/molecules/CardTotal/index.tsx
- src/components/organisms/CardRecentReported/index.tsx
- src/components/organisms/DashCounter/index.tsx
- src/helpers/extension.ts
- src/lib/services/polkadot-js.ts
- src/pages/instance/index.tsx
[MYR-2485: Handle connect wallet](https://blocksphere2020.atlassian.net/browse/MYR-2485)
> fix: added new methode create instance

- src/components/atoms/CardInstance/index.tsx
- src/pages/dashboard/instance/index.tsx
- src/pages/dashboard/settings/index.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2496
> feat: ui slicing setting

- src/components/Instance/Instance.styles.ts
- src/components/Instance/InstanceComponent.tsx
- src/components/Instance/InstanceList.tsx
- src/components/Instance/InstanceStepperModal.tsx
- src/components/ServerList/ServerList.tsx
- src/interface/ServerListInterface.ts
- src/lib/services/polkadot-js.ts
- src/pages/_document.tsx
> fix: removed unused field in ServerListProps interface

- package.json
- src/components/Instance/Instance.styles.ts
- src/components/Instance/InstanceComponent.tsx
- src/components/ServerList/ServerList.tsx
- src/components/ServerList/Shimer.tsx
- src/components/common/Blockchain/Blockchain.context.ts
- src/components/common/Blockchain/Blockchain.provider.tsx
- src/components/common/Blockchain/useBlockchain.hook.ts
- src/hooks/use-all-instances.hooks.ts
- src/hooks/use-owner-instances.hooks.ts
- src/lib/services/polkadot-js.ts
- src/pages/_app.tsx
- src/pages/index.tsx
- src/pages/instance/index.tsx
- yarn.lock
- Create blockchain context
- Move server side to client side blockchain connection
> fix: move server side to client-side blockchain connection

- src/utils/numberFormatter/index.ts
> fix: format number

- src/components/ServerList/ServerList.tsx
- src/components/atoms/CardInstance/index.tsx
> fix: typo on experiences

- package.json
- src/components/Instance/InstanceComponent.tsx
- src/components/molecules/Snackbar/Snackbar.interface.ts
- src/components/molecules/Snackbar/Snackbar.style.ts
- src/components/molecules/Snackbar/Snackbar.tsx
- src/components/molecules/Snackbar/useEnqueueSnackbar.hook.tsx
- src/hooks/use-instances.hooks.ts
- src/pages/_app.tsx
- yarn.lock
https://blocksphere2020.atlassian.net/browse/MYR-2509
> feat: add toaster if create instance failed

- src/components/Instance/InstanceStepperModal.tsx
- Changed styling and placement of text
https://blocksphere2020.atlassian.net/jira/software/c/projects/MYR/boards/12?view=detail&selectedIssue=MYR-2502
> fix: adjusted styling on text

- src/components/Instance/InstanceStepperModal.tsx
- Changed text
https://blocksphere2020.atlassian.net/browse/MYR-2502
> fix: changed text

- src/components/Instance/InstanceList.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2500
> feat: error handling auth dashboard

- .dockerignore
- .github/workflows/analyzer.yml
- .github/workflows/builder.yml
- .github/workflows/create-tags.yml
- .github/workflows/deployer.yml
- .github/workflows/mlc_config.json
- .github/workflows/rcb_config.json
- .github/workflows/release.yml
- .github/workflows/tester.yml
- .maintain/docker/Dockerfile
- next.config.js
- package.json
- ci: move registry to docker hub
- N/A
> ci: move registry to docker hub

- next.config.js
- package.json
- src/middleware.tsx
- src/pages/dashboard/help/index.tsx
- src/pages/dashboard/index.tsx
- src/pages/dashboard/instance/edit.tsx
- src/pages/dashboard/instance/index.tsx
- src/pages/dashboard/notification/index.tsx
- src/pages/dashboard/post/index.tsx
- src/pages/dashboard/post/responded.tsx
- src/pages/dashboard/settings/index.tsx
- src/pages/dashboard/user/index.tsx
- src/pages/instance/index.tsx
- yarn.lock
https://blocksphere2020.atlassian.net/browse/MYR-2520
> feat: added proxy middleware

- public/icons/index.ts
- src/components/Instance/InstanceStepperModal.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2521
> fix: update label & fix typo

- public/icons/IcBackPrimary.svg
- public/icons/index.ts
- src/components/Instance/InstanceComponent.tsx
- src/components/Instance/InstanceHeader.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2527
> fet: add back button from instace to landing page

- src/components/atoms/ListSwithAccount/index.tsx
- src/components/organisms/Header/index.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/components/organisms/ServerList/ServerList.tsx
- src/hooks/use-auth.hook.ts
https://blocksphere2020.atlassian.net/browse/MYR-2539
> feat: improve switch instance

- src/components/organisms/Header/index.tsx
- src/hooks/use-auth.hook.ts
- src/hooks/use-instances.hook.ts
> fix: bug switch instance on testnet

- src/components/atoms/ListMedian/index.tsx
- src/components/molecules/ChartDoughnut/index.tsx
- src/components/molecules/ChartPie/index.tsx
- src/components/molecules/MedianStatistics/index.tsx
- src/hooks/use-instances.hook.ts
- src/interface/ServerListInterface.ts
- src/pages/dashboard/index.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2564
> feat: integration matric dashboard

- src/components/molecules/Snackbar/Snackbar.tsx
- src/components/organisms/ServerList/ServerList.tsx
> fix: color icon snackbar

- src/hooks/use-instances.hook.ts
> fix: total post instances

- src/api/GET_TopCurrencies.ts
- src/api/GET_UsersGrowth.ts
- src/components/molecules/ChartBar/index.tsx
- src/components/molecules/ChartDoughnut/index.tsx
- src/components/molecules/ChartPie/index.tsx
- src/components/molecules/ChartTopCoint/index.tsx
- src/interface/DashboardInterface.ts
- src/interface/ServerListInterface.ts
- src/pages/dashboard/index.tsx
- src/utils/convertCamelCaseTitle/index.ts
https://blocksphere2020.atlassian.net/browse/MYR-2567
> integration wallet and social media statistics

- .github/workflows/tester.yml
- .maintain/docker/Dockerfile
> ci: update node version

- next.config.js
- src/api/GET_TopCurrencies.ts
- src/components/molecules/ChartBar/index.tsx
- src/components/molecules/ChartDoughnut/index.tsx
- src/components/molecules/ChartTopCoint/index.tsx
- src/interface/DashboardInterface.ts
- src/pages/_app.tsx
- src/pages/dashboard/index.tsx
- src/utils/dateFormatter/index.ts
https://blocksphere2020.atlassian.net/browse/MYR-2567
> fix: update revision

- src/components/organisms/Siderbar/index.tsx
- src/utils/openUrl/index.ts
https://blocksphere2020.atlassian.net/browse/MYR-2575
> feat: redirect help menu to email

- next.config.js
- src/api/GET_serversMatric.ts
- src/components/organisms/Header/index.tsx
- src/hooks/use-auth.hook.ts
- src/pages/dashboard/index.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2581
> feat: Dynamic Metric on Dashboard 

- src/components/molecules/CardEditInstance/index.tsx
- src/pages/dashboard/instance/edit.tsx
> fix: update edit instance

- src/hooks/use-auth.hook.ts
> fix: handle failed authentication

- package.json
- src/components/atoms/Button/index.tsx
- src/components/atoms/CardStaked/index.tsx
- src/components/atoms/DropdownFilter/index.tsx
- src/components/atoms/ListNetwork/index.tsx
- src/components/atoms/ListWallet/index.tsx
- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/Deregister.tsx
- src/components/molecules/Staked/TotalStaked.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/molecules/SwitchAccount/index.tsx
- src/components/molecules/SwitchNetwork/index.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/components/organisms/Instance/InstanceStepperModal.tsx
- src/constans/array.ts
- src/helpers/formatNumber.tsx
- src/pages/dashboard/settings/index.tsx
- src/styles/globals.css
- src/utils/addressFormatter/index.ts
- src/utils/colors/index.ts
- tailwind.config.js
- yarn.lock
https://blocksphere2020.atlassian.net/browse/MYR-2885
https://blocksphere2020.atlassian.net/browse/MYR-2886
https://blocksphere2020.atlassian.net/browse/MYR-2887
https://blocksphere2020.atlassian.net/browse/MYR-2888
https://blocksphere2020.atlassian.net/browse/MYR-2889
https://blocksphere2020.atlassian.net/browse/MYR-2890
https://blocksphere2020.atlassian.net/browse/MYR-2896
https://blocksphere2020.atlassian.net/browse/MYR-2897
> feat: slicing New UI Staking

- src/components/atoms/Gasfee/index.tsx
- src/components/molecules/Staked/Deregister.tsx
- src/components/molecules/Staked/TotalStaked.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/organisms/Instance/InstanceStepperModal.tsx
> feat: gas fee

- src/components/molecules/CardInstance/index.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2887
> fix: instance card space

- src/api/GET_Notifications.ts
- src/api/GET_TopCurrencies.ts
- src/api/GET_UserNonce.ts
- src/api/GET_UsersGrowth.ts
- src/api/GET_serversMetric.ts
- src/api/POST_Admin.ts
- src/components/molecules/CardEditInstance/index.tsx
- src/components/molecules/SwitchAccount/index.tsx
- src/components/organisms/Header/index.tsx
- src/components/organisms/Instance/InstanceComponent.tsx
- src/components/organisms/ServerList/ServerList.tsx
- src/hooks/use-auth.hook.ts
- src/hooks/use-instances.hook.ts
- src/interface/ServerListInterface.ts
- src/lib/services/polkadot-js.ts
- src/pages/api/auth/login.ts
- src/pages/index.tsx
- Get account and stake balance
- Add link to buy and bridge MYRIA
https://blocksphere2020.atlassian.net/browse/MYR-2901
https://blocksphere2020.atlassian.net/browse/MYR-2900
> feat: get account and stake balance

- src/components/molecules/CardEditInstance/index.tsx
- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/TotalStaked.tsx
- src/components/organisms/Header/index.tsx
- src/components/organisms/Instance/InstanceComponent.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/components/organisms/Instance/InstanceStepperModal.tsx
- src/components/organisms/ServerList/ServerList.tsx
- src/hooks/use-instances.hook.ts
- src/interface/ServerListInterface.ts
- src/lib/services/polkadot-js.ts
https://blocksphere2020.atlassian.net/browse/MYR-2903
https://blocksphere2020.atlassian.net/browse/MYR-2904
> feat: integrate stake and unstake feature

- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/Deregister.tsx
- src/components/molecules/Staked/TotalStaked.tsx
- src/components/organisms/Instance/InstanceComponent.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/components/organisms/ServerList/ServerList.tsx
- src/hooks/use-instances.hook.ts
- src/interface/ServerListInterface.ts
- src/lib/services/polkadot-js.ts
> feat: integrate deregister feature

- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/organisms/Instance/InstanceComponent.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/hooks/use-instances.hook.ts
- src/lib/services/polkadot-js.ts
> feat: integrate claim withdraw reward

- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/Deregister.tsx
- src/components/molecules/Staked/TotalStaked.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/hooks/use-instances.hook.ts
- src/interface/RewardBalanceInterface.ts
- src/interface/ServerListInterface.ts
- src/lib/services/polkadot-js.ts
- src/pages/index.tsx
> fix: remove console log

- next.config.js
- src/components/atoms/ListSwithAccount/index.tsx
- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/Deregister.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/molecules/SwitchAccount/index.tsx
- src/components/organisms/Header/index.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/components/organisms/ServerList/ServerList.tsx
- Fix copy address
- Add dynamic url to myriad app
- Filter instance
https://blocksphere2020.atlassian.net/browse/MYR-2906
https://blocksphere2020.atlassian.net/browse/MYR-2907
> feat: copy address & filter instance

- src/api/GET_Currencies.ts
- src/api/GET_Network.ts
- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/organisms/Instance/InstanceComponent.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/components/organisms/Instance/InstanceStepperModal.tsx
- src/components/organisms/ServerList/ServerList.tsx
- src/hooks/use-instances.hook.ts
- src/interface/CurrencyInterface.ts
- src/interface/NetworkInterface.ts
- src/interface/RewardBalanceInterface.ts
- src/interface/ServerListInterface.ts
- src/lib/services/polkadot-js.ts
https://blocksphere2020.atlassian.net/browse/MYR-2902
> feat: implement withdraw reward feature

- src/components/molecules/Staked/UnclaimReward.tsx
- src/hooks/use-instances.hook.ts
- src/interface/CurrencyInterface.ts
- src/interface/RewardBalanceInterface.ts
- src/lib/services/polkadot-js.ts
> fix: updated amount data type

- src/components/organisms/ServerList/ServerList.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2911
> feat: sort instance

- src/api/GET_Currencies.ts
- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/Deregister.tsx
- src/components/molecules/Staked/TotalStaked.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/hooks/use-instances.hook.ts
- src/lib/services/polkadot-js.ts
> fix: implement gas fee on stake, claim reward, and deregister card 

- src/hooks/use-instances.hook.ts
> fix: update account balance when claim reward

- src/components/molecules/Staked/TotalStaked.tsx
> fix: hide buy myria when unstaked modal showing

- src/components/atoms/ListWallet/index.tsx
- src/components/molecules/CardInstance/index.tsx
- src/components/molecules/Staked/TotalStaked.tsx
- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/molecules/SwitchNetwork/index.tsx
- src/components/organisms/Header/index.tsx
- src/components/organisms/Instance/InstanceComponent.tsx
- src/components/organisms/Instance/InstanceList.tsx
- src/components/organisms/Instance/InstanceStepperModal.tsx
- src/components/organisms/ServerList/ServerList.tsx
- src/helpers/formatNumber.tsx
- src/hooks/use-instances.hook.ts
- src/interface/CurrencyInterface.ts
- src/lib/services/polkadot-js.ts
https://blocksphere2020.atlassian.net/browse/MYR-2910
> feat: implement create instance with stake amount

- src/components/organisms/Instance/InstanceStepperModal.tsx
- src/pages/dashboard/settings/index.tsx
> feat: add link deployment guide

- src/components/organisms/Instance/InstanceStepperModal.tsx
> fix: handle create instance

- src/components/organisms/ServerList/ServerList.tsx
> feat: change query to apps from rpc to instance

- .maintain/docker/Dockerfile
- .maintain/docker/docker-compose.yml
- package.json
> ci: change email

- src/api/GET_stats.ts
- src/components/molecules/MedianStatistics/index.tsx
- src/hooks/use-dashboard.hook.ts
- src/interface/ServerListInterface.ts
- src/pages/dashboard/index.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2916
> fix: fixed average endpoint

- src/components/molecules/CardInstanceLeft/index.tsx
- src/components/molecules/MedianStatistics/index.tsx
- src/components/organisms/DashCounter/index.tsx
> feat: change wording from experience to timeline

- .github/workflows/cicd.yaml
> ci: change secret for DNS

- src/components/molecules/CardInstance/index.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2938
> feat: add total staked to instance card

- src/components/molecules/Staked/UnclaimReward.tsx
- src/components/molecules/SwitchNetwork/index.tsx
- src/hooks/use-instances.hook.ts
https://blocksphere2020.atlassian.net/browse/MYR-2962
> feat: switch network in modal staking reward

- src/components/organisms/ServerList/ServerList.tsx
https://blocksphere2020.atlassian.net/browse/MYR-2983
> fix: sort instance
